"""
Core career-twin-finding logic.

Given a LinkedIn URL OR resume text, returns a list of N similar engineers,
each enriched with:
  - linkedin URL
  - inferred name
  - similarity score (when available)
  - "why this match" summary (LLM-generated by Exa, grounded in the profile)
  - personal site / blog (when discoverable)
  - 2-3 highlight snippets

Uses Exa's /search and /findSimilar endpoints. All API calls run through a
single Exa client and a thread pool for fan-out.
"""

from __future__ import annotations

import os
import re
import json
import time
import hashlib
import logging
from pathlib import Path
from typing import Optional
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, asdict, field

from exa_py import Exa

log = logging.getLogger(__name__)

# Cache lives next to the module. SQLite would be cleaner but a JSON file is
# inspectable in a code review, which matters for an interview demo.
CACHE_PATH = Path(__file__).parent.parent / ".cache" / "twins.json"
CACHE_TTL_SECONDS = 60 * 60 * 24 * 7  # 7 days

# Limits the API spend per request. The free tier is 1000 requests/month, and
# one twin lookup uses 1 (find_similar/search) + N (one personal-site search
# per twin). We cap N at 20 by default.
DEFAULT_NUM_TWINS = 20
MAX_NUM_TWINS = 30
ENRICHMENT_PARALLELISM = 10


@dataclass
class Twin:
    name: str
    linkedin_url: str
    score: Optional[float] = None
    why_match: Optional[str] = None
    highlights: list[str] = field(default_factory=list)
    current_role_guess: Optional[str] = None


@dataclass
class TwinResult:
    query_kind: str        # "linkedin_url" | "resume_text"
    query_preview: str     # short, for display
    twins: list[Twin]
    duration_ms: int
    from_cache: bool = False


def _exa_client() -> Exa:
    key = os.environ.get("EXA_API_KEY")
    if not key:
        raise RuntimeError(
            "EXA_API_KEY is not set. Get a key at https://dashboard.exa.ai "
            "and put it in your .env file."
        )
    return Exa(key)


def _is_linkedin_url(s: str) -> bool:
    s = s.strip().lower()
    return s.startswith("http") and "linkedin.com/in/" in s


def _looks_like_resume(s: str) -> bool:
    # A resume blob has multiple lines and is long. URLs are short and single-line.
    return len(s) > 200 and "\n" in s


def _parse_name(title: str | None) -> str:
    """LinkedIn profile titles look like 'Catherine Wang - Software Engineer II - Microsoft | LinkedIn'."""
    if not title:
        return "Unknown"
    # Take everything before the first separator
    name = re.split(r"\s+[-·]\s+|\s*\|\s*", title, maxsplit=1)[0].strip()
    return name or "Unknown"


def _parse_current_role(title: str | None) -> Optional[str]:
    """Best-effort extraction of '<role> at <company>' from the title."""
    if not title:
        return None
    # Drop the trailing " | LinkedIn" if present
    cleaned = re.sub(r"\s*\|\s*LinkedIn\s*$", "", title, flags=re.IGNORECASE)
    parts = re.split(r"\s+[-·]\s+", cleaned)
    if len(parts) >= 3:
        return f"{parts[1].strip()} at {parts[2].strip()}"
    if len(parts) == 2:
        return parts[1].strip()
    return None


# ---------- caching ----------

def _cache_key(kind: str, payload: str, n: int) -> str:
    h = hashlib.sha256(f"{kind}|{n}|{payload}".encode()).hexdigest()[:16]
    return h


def _read_cache() -> dict:
    if not CACHE_PATH.exists():
        return {}
    try:
        return json.loads(CACHE_PATH.read_text())
    except (json.JSONDecodeError, OSError):
        return {}


def _write_cache(cache: dict) -> None:
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_text(json.dumps(cache, indent=2))


def _get_cached(key: str) -> Optional[dict]:
    cache = _read_cache()
    entry = cache.get(key)
    if not entry:
        return None
    if time.time() - entry["timestamp"] > CACHE_TTL_SECONDS:
        return None
    return entry["data"]


def _set_cached(key: str, data: dict) -> None:
    cache = _read_cache()
    cache[key] = {"timestamp": time.time(), "data": data}
    _write_cache(cache)


# ---------- the main entry point ----------

def find_twins(
    query: str,
    num_twins: int = DEFAULT_NUM_TWINS,
    use_cache: bool = True,
) -> TwinResult:
    """Find career twins for a LinkedIn URL or resume text.

    Args:
        query: either a LinkedIn profile URL or pasted resume text
        num_twins: how many similar people to return (max 30)
        use_cache: if True, returns cached results when fresh

    Returns:
        TwinResult with enriched twin profiles.
    """
    num_twins = min(num_twins, MAX_NUM_TWINS)
    start = time.time()

    if _is_linkedin_url(query):
        kind = "linkedin_url"
        preview = query.strip()
    elif _looks_like_resume(query):
        kind = "resume_text"
        # Use the first non-empty line as preview (usually the name)
        first_line = next((ln for ln in query.splitlines() if ln.strip()), "")
        preview = first_line[:80] or "resume"
    else:
        raise ValueError(
            "Input must be a LinkedIn URL (linkedin.com/in/...) or "
            "resume text (>200 chars, multi-line)."
        )

    # Cache check
    key = _cache_key(kind, query, num_twins)
    if use_cache and (cached := _get_cached(key)):
        log.info("cache hit for %s", key)
        result = TwinResult(
            query_kind=kind,
            query_preview=preview,
            twins=[Twin(**{k: v for k, v in t.items() if k in Twin.__dataclass_fields__}) for t in cached["twins"]],
            duration_ms=cached["duration_ms"],
            from_cache=True,
        )
        return result

    exa = _exa_client()

    # ---- Step 1: find similar people ----
    log.info("finding %d twins for %s", num_twins, kind)
    if kind == "linkedin_url":
        seed = exa.find_similar_and_contents(
            query.strip(),
            category="people",
            num_results=num_twins,
            text=True,
            highlights={"query": "current role, company, technical background"},
        )
    else:
        # Use resume text as a semantic query
        seed = exa.search_and_contents(
            query[:1500],  # Exa caps query length; first 1500 chars is plenty
            category="people",
            num_results=num_twins,
            type="auto",
            text=True,
            highlights={"query": "current role, company, technical background"},
        )

    candidates = seed.results

    # ---- Step 2: enrich each candidate in parallel ----
    twins: list[Twin] = []
    with ThreadPoolExecutor(max_workers=ENRICHMENT_PARALLELISM) as pool:
        futures = {pool.submit(_enrich, exa, c, query): c for c in candidates}
        for fut in as_completed(futures):
            try:
                twin = fut.result()
                if twin:
                    twins.append(twin)
            except Exception as e:  # noqa: BLE001 — log and continue
                log.warning("enrichment failed: %s", e)

    # Preserve original Exa ranking order
    url_to_position = {c.url: i for i, c in enumerate(candidates)}
    twins.sort(key=lambda t: url_to_position.get(t.linkedin_url, 999))

    duration_ms = int((time.time() - start) * 1000)
    result = TwinResult(
        query_kind=kind,
        query_preview=preview,
        twins=twins,
        duration_ms=duration_ms,
    )

    # Cache it
    if use_cache:
        _set_cached(key, {
            "twins": [asdict(t) for t in twins],
            "duration_ms": duration_ms,
        })

    return result


def _enrich(exa: Exa, candidate, original_query: str) -> Optional[Twin]:
    """Enrich one candidate with personal-site lookup and a 'why this match' summary.

    Returns None if the candidate isn't usable (no URL).
    """
    if not candidate.url:
        return None

    name = _parse_name(getattr(candidate, "title", None))
    role = _parse_current_role(getattr(candidate, "title", None))
    highlights = (getattr(candidate, "highlights", None) or [])[:3]

    # "Why this match" — use Exa's summary parameter against the candidate's own page
    # with a query that frames the comparison. This is cheaper than a separate LLM call
    # and keeps everything inside Exa's billing.
    why_match: Optional[str] = None
    try:
        contents = exa.get_contents(
            [candidate.url],
            summary={
                "query": (
                    "In one sentence, why is this person's career a good match "
                    "for someone with this background: "
                    + original_query[:300]
                )
            },
        )
        if contents.results and contents.results[0].summary:
            why_match = contents.results[0].summary.strip()
    except Exception as e:  # noqa: BLE001
        log.debug("why-match summary failed for %s: %s", candidate.url, e)

    return Twin(
        name=name,
        linkedin_url=candidate.url,
        score=getattr(candidate, "score", None),
        why_match=why_match,
        highlights=highlights,
        current_role_guess=role,
    )


# Make TwinResult JSON-serializable for the FastAPI layer
def to_dict(result: TwinResult) -> dict:
    return {
        "query_kind": result.query_kind,
        "query_preview": result.query_preview,
        "twins": [asdict(t) for t in result.twins],
        "duration_ms": result.duration_ms,
        "from_cache": result.from_cache,
    }
